ecommerce/ecommerce_project/cart_app/urls.py
from django.urls import path
from . import views

app_name = 'cart_app'

urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
]

ecommerce/ecommerce_project/ecommerce_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("shop/", include('shop_app.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart_app.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/ecommerce_project/search_app/urls.py
from django.urls import path
from . import views

app_name = 'search_app'

urlpatterns = [
    path('', views.SearchResult, name='SearchResult'),
]

ecommerce/ecommerce_project/shop_app/urls.py
from . import views
from django.urls import path

app_name = 'shop_app'

urlpatterns = [
    path('', views.allProductCat, name='allProductCat'),
    path('<slug:cat_slug>/', views.allProductCat, name='products_by_category'),
    path('<slug:cat_slug>/<slug:pro_slug>/', views.proDetail, name='procatDetail'),
]

ecommerce/ecommerce_project/cart_app/models.py
from django.db import models

from shop_app.models import Product
# Create your models here.

class Cart(models.Model):
    objects = None
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)

class Cart_Items(models.Model):
    objects = None
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'Cart_Items'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecommerce/ecommerce_project/search_app/models.py
from django.db import models

# Create your models here.

ecommerce/ecommerce_project/shop_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    objects = None
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('shop_app:products_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    objects = None
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('shop_app:procatDetail', args=[self.category.slug, self.slug])

    def __str__(self):
        return '{}'.format(self.name)

ecommerce/ecommerce_project/cart_app/views.py
from django.shortcuts import render, redirect, get_object_or_404

from shop_app.models import Product
from . models import Cart, Cart_Items
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
    cart.save()

    try:
        cart_items = Cart_Items.objects.get(product=product, cart=cart)
        if cart_items.quantity < cart_items.product.stock:
            cart_items.quantity += 1

        cart_items.save()
    except Cart_Items.DoesNotExist:
        cart_items = Cart_Items.objects.create(product=product, quantity=1, cart=cart)
        cart_items.save()

    return redirect('cart_app:cart_detail')

def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = Cart_Items.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity

    except ObjectDoesNotExist:
        pass

    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))

def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_items = Cart_Items.objects.get(product=product, cart=cart)
    if cart_items.quantity > 1:
        cart_items.quantity -= 1
        cart_items.save()
    else:
        cart_items.delete()
    return redirect('cart_app:cart_detail')

def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_items = Cart_Items.objects.get(product=product, cart=cart)
    cart_items.delete()
    return redirect('cart_app:cart_detail')

ecommerce/ecommerce_project/search_app/views.py
from django.shortcuts import render

from shop_app.models import Product
from django.db.models import Q

# Create your views here.

def SearchResult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        return render(request, 'search.html', {'query': query, 'products': products})

ecommerce/ecommerce_project/shop_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from . models import Category, Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage


# Create your views here.
def allProductCat(request, cat_slug=None):
    cat_page = None
    products_list = None
    if cat_slug != None:
        cat_page = get_object_or_404(Category, slug=cat_slug)
        products_list = Product.objects.all().filter(category=cat_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)

    paginator = Paginator(products_list, 6)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except(EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request, 'category.html', {'category': cat_page, 'products': products})

def proDetail(request, cat_slug, pro_slug):
    try:
        product = Product.objects.get(category__slug=cat_slug, slug=pro_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html', {'product': product})

ecommerce/ecommerce_project/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="shortcut icon" href="{% static 'image/logo.png' %}" type="image/x-icon">
<!--    <script src="https://kit.fontawesome.com/a076d05399.js"></script>-->
    <script src="https://kit.fontawesome.com/ef23d5943b.js" crossorigin="anonymous"></script>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Nunito:wght@400;500&display=swap');
    </style>
</head>
<body>
<div>
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

ecommerce/ecommerce_project/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
  This is the Cart Page. proceed to review your items and place the order - ABC Shop
{% endblock %}

{% block title %}
  Cart - ABC Shop pvt, ltd.
{% endblock %}

{% block content %}
{% if not cart_items %}
<div>
  <div class="text-center">
    <br>
    <h1 class="text-center" style="font-size: 16px;text-transform: uppercase;letter-spacing: 0.1em;font-weight: bolder;">Your shopping Cart is Empty...</h1>
    <br>
    <p class="text-center">Please click <a href="{% url 'shop_app:allProductCat' %}">Here</a>to continue shopping.</p>
  </div>
</div>
{% else %}
<div>
  <div class="text-center">
    <br>
    <h1 class="text-center" style="font-size: 16px;text-transform: uppercase;letter-spacing: 0.1em;font-weight: bolder;">Your Shopping Cart</h1>
    <br>
  </div>
  <div class="row" style="color: #000;font-size: 12px;">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
      <table class="table" style="min-width: 400px;font-size: 14px;">
        <thead style="font-weight: normal;text-transform: uppercase;letter-spacing: 0.1em;background-color: #f8f8fa !important;">
          <tr>
            <th colspan="5">Your Items</th>
          </tr>
        </thead>
        <tbody>
          {% for cart_item in cart_items %}
          <tr>
            <td>
              <a href="{{cart_item.product.get_url}}">
                <img src="{{cart_item.product.image.url}}" alt="{{cart_item.product.name}}" class="float-left rounded" style="width: 100px;height: 100px;"></a>
            </td>
            <td class="text-left">
              {{cart_item.product.name}}
              <br>
              SKU: {{cart_item.product.id}}
              <br>
              Price: <strong>&#8377;{{cart_item.product.price}}</strong>
              <br>
              Qty: {{cart_item.quantity}} x {{cart_item}}
            </td>
            <td>
              <strong>&#8377;{{cart_item.sub_total}}</strong>
            </td>
            {% if cart_item.quantity < cart_item.product.stock %}
            <td>
              &nbsp;<a href="{% url 'cart_app:add_cart' cart_item.product.id %}" style="text-decoration: none;"><i class="fa fa-plus" style="text-decoration: none;color: #868e96 !important;"></i></a>
              <br>
              &nbsp;<a href="{% url 'cart_app:cart_remove' cart_item.product.id %}" style="text-decoration: none;"><i class="fa fa-minus" style="text-decoration: none;color: #868e96 !important;"></i></a>
              <br>
              &nbsp;<a href="{% url 'cart_app:full_remove' cart_item.product.id %}" style="text-decoration: none;color: #868e96 !important;"><i class="fa fa-trash" style="text-decoration: none;color: #868e96 !important;"></i></a>
            </td>
            {% else %}
            <td>
              &nbsp;<a href="{% url 'cart_app:cart_remove' cart_item.product.id %}" style="text-decoration: none;"><i class="fa fa-minus" style="text-decoration: none;color: #868e96 !important;"></i></a>
              <br>
              &nbsp;<a href="{% url 'cart_app:full_remove' cart_item.product.id %}" style="text-decoration: none;color: #868e96 !important;"><i class="fa fa-trash" style="text-decoration: none;color: #868e96 !important;"></i></a>
              <br>
            </td>
            {% endif %}
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
      <table class="table" style="min-width: 400px;font-size: 14px;">
        <thead style="font-weight: normal;text-transform: uppercase;letter-spacing: 0.1em;background-color: #f8f8fa !important;">
          <tr>
            <th>
              Checkout
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              Please review your shopping cart items before proceeding with the order payment.
            </td>
          </tr>
          <tr>
            <td class="text-left">
              Your Total is: <strong>&#8377;{{total}}</strong>
            </td>
          </tr>
        </tbody>
      </table>
      <div style="color: #000;font-size: 12px;">
        <a href="{% url 'shop_app:allProductCat' %}" class="btn btn-secondary btn-block" style="margin-top: 5px;">Continue Shopping</a>
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endblock %}

ecommerce/ecommerce_project/templates/category.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:150 }}
    {% else %}
        Welcome to ABC Shop where you can buy different items....
    {% endif %}
{% endblock %}

{% block title %}
    {% if category %}
        {{ category.name }} - ABC Shop
    {% else %}
        See our New Collections - ABC Shop
    {% endif %}
{% endblock %}

{% block content %}
{% if category %}
    <div>
      <div class="row" style="padding-top: 15px;">
          <div style="color: #000;font-size: 12px">
            <p><a style="text-decoration: none;" href="{% url 'shop_app:allProductCat' %}">Our Collections</a></p>
          </div>
      </div>
    </div>
{% endif %}

<div style="color: #000;font-size: 12px">
    {% if category %}
    <img style="width: 10%;height: auto;" src="{{category.image.url}}" alt="{{category.name}}">
</div>
<br>
<div>
    <h1 class="text-center" style="font-size: 16px;text-transform: uppercase;letter-spacing: 0.1em;font-weight: bolder;">{{category.name}}</h1>
    <p class="text-justify">{{category.description}}</p>
</div>
<div>
    {% else %}
    <img class="container-fluid" style="width: 100%;height: auto;padding: 5px;" src="{% static 'image/banner3.png' %}" alt="our products" width="auto">
</div>
    <br>
<div>
    <h1 class="text-center" style="font-size: 16px;text-transform: uppercase;letter-spacing: 0.1em;font-weight: bolder;">Our products collections</h1>
    <p class="text-justify">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.</p>
</div>
    {% endif %}

<div class="container">
    <div class="row" style="color: #000;font-size: 12px">
        {% for product in products.object_list %}
        <div class="col-9 col-sm-12 col-md-4 col-lg-4" style="margin-bottom: 10px;">
            <div class="card text-center" style="width: 18rem; height: auto;">
                <a href="{{product.get_url}}"><img class="card-img-top" style="width: 100%;height: auto;" src="{{product.image.url}}" alt="{{product.name}}"></a>
                <div class="card-body">
                    <h4 style="font-size: 14px;text-transform: uppercase;letter-spacing: 0.1em;">{{product.name}}</h4>
                    <p>&nbsp;<strong>&#8377;{{product.price}}</strong></p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div>
        {% if products.paginator.num_pages > 1 %}
        <hr>
        <div class="text-center">
            {% for page in products.paginator.page_range %}
            <a href="?page={{page}}" class="btn btn-light btn-sm {% if products.number == page %} active {% endif %}">{{page}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</div>

{% endblock %}

ecommerce/ecommerce_project/templates/footer.html
<br>
<div class="contain-fluid fixed-bottom my_footer">
  <p class="text-center">&copy; ABC shop pvt ltd. All rights Reserved</p>
</div>

ecommerce/ecommerce_project/templates/header.html
{% load static %}
<header class="container-fluid sticky-top my-header">
  <a class="container" style="text-decoration: none;" href="{% url 'shop_app:allProductCat' %}"><img src="{% static 'image/logo.png' %}" alt="logo_image" width="60px" height="60px">
      <a style="text-decoration: none;padding-right: 20px;font-weight: bolder;color: whitesmoke;">ABC Shopping</a></a>
</header>

ecommerce/ecommerce_project/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shop_app:allProductCat' %}"><i class="fa fa-home"></i></a>
        </li>
        <li class="nav-item dropdown {% if 'shop_app' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown">
            Shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'shop_app:allProductCat' %}">All Products</a></li>
            {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
            {% endfor %}
          </ul>
        </li>
        {% for cat in links %}
          <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
        {% endfor %}

        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart_app:cart_detail' %}"><i class="fa fa-shopping-cart" style="font-size:20px;color:#2196F3"></i>{% if item_count > 0 %}({{item_count}}){% endif %}</a>
        </li>

      </ul>
      <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" autocomplete="off" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

ecommerce/ecommerce_project/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    {{ product.description|truncatewords:150 }}
{% endblock %}

{% block title %}
    {{ product.name }} - ABC Shop
{% endblock %}

{% block content %}

<div class="row" style="padding-top: 15px;padding-bottom: 15px;">
    <div style="color: #000;font-size: 12px;">
        <p> <a style="text-decoration: none;" href="{% url 'shop_app:allProductCat' %}">Home</a> > <a style="text-decoration: none;" href="{{product.category.get_url}}">{{product.category}}</a> > {{product.name}}</p>
    </div>
</div>
<div class="container">
<br>
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <div style="min-width: 18rem;">
                <img src="{{product.image.url}}" alt="{{product.name}}" style="width: 50%;height: auto;">
            </div>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <h1 style="font-size: 16px;text-transform: uppercase;letter-spacing: 0.1em;padding-top: 15px;padding-bottom: 10px;">{{product.name}}</h1>
            <p> &nbsp;<strong>&#8377;{{product.price}}</strong></p>
            <p style="font-size: 16px;text-transform: uppercase;letter-spacing: 0.1em;font-weight: bolder;">Product Description</p>
            <p class="text-justify" style="padding-right: 20px">{{product.description}}</p>
            {% if product.stock <= 0 %}
            <p class="text-justify" style="padding-right: 20px"><b>Out of Stock</b></p>
            {% else %}
            <a class="btn btn-secondary" href="{% url 'cart_app:add_cart' product.id %}"><b>Add to Cart</b></a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

ecommerce/ecommerce_project/templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
  here you have variety of products... - ABC Shop
{% endblock %}

{% block title %}
  See our New Collections - ABC Shop
{% endblock %}

{% block content %}
<div>
  <p class="text-center" style="padding-top: 20px;">Showing results for <strong>"{{query}}"</strong></p>
</div>
<div class="container">
    <div class="row" style="color: #000;font-size: 12px">
        {% for product in products %}
        <div class="col-9 col-sm-12 col-md-4 col-lg-4" style="margin-bottom: 10px;">
            <div class="card text-center" style="width: 18rem; height: auto;">
                <a href="{{product.get_url}}"><img class="card-img-top" style="width: 100%;height: auto;" src="{{product.image.url}}" alt="{{product.name}}"></a>
                <div class="card-body">
                    <h4 style="font-size: 14px;text-transform: uppercase;letter-spacing: 0.1em;">{{product.name}}</h4>
                    <p>&nbsp;<strong>&#8377;{{product.price}}</strong></p>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="row" style="color: #000;font-size: 16px;">
            <p class="text-center" style="padding-top: 20px;padding-left: 30px;font-size: 25px;">Sorry, no results found!</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}